# Generated by Buildr 1.3.3, change to your liking
# Standard maven2 repository

repositories.remote << 'http://repo2.maven.org/maven2'
repositories.remote << 'http://www.ibiblio.org/maven2'

KRYO = artifact( 'com.esotericsoftware:kryo:jar:1.1-SNAPSHOT' ).from( file( 'lib/kryo-1.1-SNAPSHOT.jar' ) )
REFLECTASM = artifact('com.esotericsoftware:reflectasm:jar:0.8').from(file('lib/reflectasm-0.8.jar'))
MINLOG = artifact('com.esotericsoftware:minlog:jar:1.2').from(file('lib/minlog-1.2.jar'))
ASM = 'asm:asm:jar:3.2'

CLANG = 'commons-lang:commons-lang:jar:2.4' # tests of javolution-serializer, xstream-serializer



desc 'Kryo/binary serialization strategy'
define 'kryo-serializers' do
  project.group = 'kryo'
  project.version = '0.1-SNAPSHOT'

  compile.using :source=>'1.5', :target=>'1.5'
  test.using :testng
  package :sources, :javadoc
  package_with_javadoc

  compile.with( KRYO, REFLECTASM, ASM, MINLOG )
  test.with( compile.dependencies, CLANG )
  package :jar

end
