# Generated by Buildr 1.3.3, change to your liking
# Standard maven2 repository

repositories.remote << 'http://repo2.maven.org/maven2'
repositories.remote << 'http://www.ibiblio.org/maven2'

KRYO = artifact( 'kryo:kryo:jar:1.0' ).from( file( 'lib/kryo-1.0.jar' ) )
ASM = 'asm:asm:jar:3.2'
MINLOG = artifact( 'kryo:minlog:jar:1.1' ).from( file( 'lib/minlog-1.1.jar' ) )

CLANG = 'commons-lang:commons-lang:jar:2.4' # tests of javolution-serializer, xstream-serializer



desc 'Kryo/binary serialization strategy'
define 'kryo-hello' do
  project.group = 'kryo'
  project.version = '0.1-SNAPSHOT'

  compile.using :source=>'1.5', :target=>'1.5'
  test.using :testng
  package :sources, :javadoc
  package_with_javadoc

  compile.with( KRYO, ASM, MINLOG )
  test.with( compile.dependencies, CLANG )
  package :jar

end
